export const CONFIG = {
  BACKEND_URL: process.env.PLASMO_PUBLIC_BACKEND_URL,
  AUTH_TOKEN_COOKIE_KEY: process.env.PLASMO_PUBLIC_AUTH_TOKEN_COOKIE_KEY,
  HEVY_API_URL: process.env.PLASMO_PUBLIC_HEVY_API_URL
}
